window.WARI_CLIPS = [
  {id:'1ojMWwiiVQ802vFLUdURbA2VpcVWvJkH5',title:'मा. ना. श्री. प्रकाश आबिटकर',size:'22 MB'},
  {id:'1wVfsX3h2JCWpxJ_-kU8gQGYIi62WTLKs',title:'NIROGI GAV',size:'144 MB'},
  {id:'1zor7NyMKYgQ_9kSsuHjaliVHnMZrLpxm',title:'Health Services Song',size:'1.07 GB'},
  {id:'1MyBQFSl-mmelXDXGpCfR_6FkVfVZunqW',title:'DOCUMENTRY MAHA AROGYA',size:'550 MB'},
  {id:'1ZcSV98fk-dALRzSsp0lU5erHkmPjTzhe',title:'प्रार्थना',size:'122 MB'},
  {id:'10nefTFzqRdZrRoY0TwWnrwILWne6n6hj',title:'Maza Gaon - teaser',size:'286 MB'},
  {id:'1PFL0spzYx4n-izXQW174r_A3HOsDxRW7',title:'Maaz Gaon 02',size:'154 MB'},
  {id:'1Fqk8z9NiQfbQABY4rOZbwmruNYKYOc1R',title:'Kasa Kay Main Film',size:'194 MB'},
  {id:'1y1XlqwlMcOF1n9WxPFDYKxBGZib9sOfZ',title:'आरोग्य क्लिप 9',size:'7 MB'},
  {id:'1KERD_Q78FE3j_rfhmwn9yRfYNbmd5MgS',title:'Still Birth Audio Jingle',size:'41 MB'},
  {id:'1Aw3wCatw5jPxPdqu0bTUmA8-pfIsy5-q',title:'TB haay ka',size:'73 MB'},
  {id:'1xJJ4rZDo1gG7dNyv8kFnrkvgjk4NNM6P',title:'Swachha Nahi Gaav',size:'481 MB'},
  {id:'1gSeEuPSuTV7Qy4g907vVX2IkqCKYg-xC',title:'टी बी हाय का तपासणी केली हाय का',size:'160 MB'},
  {id:'125cMMDiQ5XqZlfGEt1jxyL9XDBfrpDbf',title:'Still Birth Video-01',size:'105 MB'},
  {id:'1KZ03mwWJYym8ubzEJTEZlLXoXIFbcqI7',title:'जन्म मृत्यू नोंदणी करा वेळेत',size:'58 MB'},
  {id:'1NNjYNcQEo0z6ZCW62mQ_xukpc6adlaZj',title:'महात्मा ज्योतिराव फुले जन आरोग्य योजना',size:'4 MB'},
  {id:'1Wa8_DrQccW1CTpPGtYqKntaeTtUmxsbT',title:'Hypertension',size:'24 MB'},
  {id:'1ptXfENG1q-7C-vKRZ5dxEzlBD1mAngQr',title:'टीबी विरुद्ध पुढाकार, घ्या हो सर्वांनी',size:'771 MB'},
  {id:'1TEde_dG_VQaD4wd_-TN_zyeXuzq5OK_B',title:'STEMI Maharashtra Project',size:'15 MB'},
  {id:'1l-vjWg5-QTYQjK42JcBO_o3qUucFCbiY',title:'टीबी मुक्त भारत अभियान - लोकगीत',size:'108 MB'},
  {id:'1D7jgW1X9PEt95VW9sdHO9wyA0jJe6_N2',title:'टीबी मुक्त भारत अभियान रॅप',size:'115 MB'},
  {id:'1sWnXRYiI7nIFOArT4Ik56ZlUaDtnuL6S',title:'आरोग्य क्लिप 22',size:'63 MB'},
  {id:'1G7IfExmMSvUQhFkLEKy-byJ6P9VrwAgl',title:'आरोग्य क्लिप 23',size:'167 MB'},
  {id:'1be5q_iv7SoIDfEBhrB-uxu3EtzDNHJkZ',title:'आरोग्य क्लिप 24',size:'411 MB'},
  {id:'1rpQ1rbr3DmR0AO_JM18MhdzKC8sCQXvl',title:'आरोग्य क्लिप 25',size:'27 MB'},
  {id:'1wlrSZSikN5q3ilhv4TgTqHvr2cEdM7rk',title:'आरोग्य क्लिप 26',size:'11 MB'},
  {id:'1hmxOn_YEnzTxMonJIBs_MhWDZOi1rtGI',title:'आरोग्य क्लिप 27',size:'69 MB'},
  {id:'15hsr0Y8uDEByF9hfnAh-DBj50zfpcKyE',title:'Just One Sign - Rebirth Green Corridor Short Film Competition 2018',size:'67 MB'},
  {id:'1Tktrs7JoH5FjhwnH2vllvBs0oxRiJK7T',title:'Rest In Peace',size:'79 MB'}
];
